bounswe/bounswe2022group5

practice_app/README.md
I created a new read-me file for our practice-app.
=> Created Read me for practice-app.

practice-app/practice_app/urls.py, practice-app/user/serializers.py, practice-app/user/urls.py, practice-app/user/views.py
As I mentioned in the issue [#81](https://github.com/bounswe/bounswe2022group5/issues/81), APIs for listing all users or a spesific user and creating user are implemented. You can view the details of endpoints in the issue or [documentation](https://documenter.getpostman.com/view/14834467/UyxdLpit).
-username
-email
-password
* Using endpoint "user/userList":
GET request: View all Users
POST request: Create a User
* Using endpoint "user/userDetail":
GET request: View User Detail
=> User APIs are initially implemented

practice-app/category/models.py, practice-app/comment_info/serializers.py, practice-app/comment_info/urls.py, practice-app/comment_info/views.py, practice-app/practice_app/urls.py
A very first implementation of the API. Satisfies the requirements at the moment, but it can be improved by the time.
@palahb and @oguzhandemirelx, could you please take a look at it before merging with the master branch?
=> Practice app/feature/comment info #84 initial creation of API.

practice-app/post/models.py, practice-app/post/serializers.py, practice-app/post/urls.py, practice-app/post/views.py
I made some commits and pushes throughout the day.  They now can be merged into master. Additions will be made upcoming days.
*covid19cases* field of the Post Model changed from IntegerField to JSONField. 
GET and POST requests are implemented. 
- GET: Retrieves all posts from the database.
- POST: Creates a new Post with given inputs.
**To do:**
- Fetching COVID19 data from an external API will be added.
Please, refer to the [issue #83](https://github.com/bounswe/bounswe2022group5/issues/83).
=> Practice app/feature/post #83

practice-app/category/forms.py, practice-app/category/models.py, practice-app/category/serializers.py, practice-app/category/templates/base.html, practice-app/category/templates/createForm.html, practice-app/category/templates/index.html, practice-app/category/templates/listCategories.html, practice-app/category/urls.py, practice-app/category/views.py, practice-app/practice_app/urls.py
I completed the initial structure of the /category/ endpoint. You can review my version and merge with the main branch. 
Some uncompleted tasks: 
- Implementing unit tests for the API
- Preparing a documentation for functionalities of the API
=> Category APIs are implemented

practice-app/post/forms.py, practice-app/post/static/cards.css, practice-app/post/static/index.css, practice-app/post/static/references.txt, practice-app/post/templates/base.html, practice-app/post/templates/create.html, practice-app/post/templates/get.html, practice-app/post/views.py
Done:
- UI improved.
To do:
- Fetch user info from the session if applicable after merging.
I am going to work on the *todo* as soon as the branch merges.
=> Practice app/feature/post #102

practice-app/article_info/forms.py, practice-app/article_info/templates/error_article_info.html, practice-app/article_info/templates/forms_article_info.html, practice-app/article_info/templates/updated_article_info.html, practice-app/article_info/templates/view_article_info.html, practice-app/article_info/urls.py, practice-app/article_info/views.py
The conflicts in pull request #107 are resolved by opening a clean branch.
@canberkboun9 , @oguzhandemirelx  Can you please review?
=> Practice-app/feature/article-info #97-2

practice-app/article/forms.py, practice-app/article/urls.py, practice-app/article/views.py
I cloned the newest version of the master, opened my branch and made my commit and push for the `/article/api` endpoint.
- GET and POST endpoints of the API are implemented.
- Tests in Postman are conducted.
- No conflicts occured.
- 
- Will work on unit tests and front-end (that will be mentioned in new issues for simplicity)
Reviewers: @makifyilmaz  @bbenginbestas can you review my implementation, please?
issue: [#105](https://github.com/bounswe/bounswe2022group5/issues/105)
=> Practice app/feature/article-#105

practice-app/comment/forms.py, practice-app/comment/serializers.py, practice-app/comment/templates/comment.html, practice-app/comment/templates/listComments.html, practice-app/comment/urls.py, practice-app/comment/views.py
Some enhancements referred in the comments of the issue #112 are implemented:
- Error messages for various cases are shown in the frontend.
- Time stamp information is shown in a more proper way.
- Some changes in HTTP response codes are implemented.
=> Improvements in the Comment Frontend

practice-app/article_info/forms.py, practice-app/article_info/templates/updated_article_info.html, practice-app/article_info/templates/view_article_info.html, practice-app/article_info/tests.py, practice-app/article_info/tests/test_forms.py, practice-app/article_info/tests/test_urls.py, practice-app/article_info/tests/test_views.py, practice-app/article_info/urls.py, practice-app/article_info/views.py
Unit tests for article-info endpoint are implemented. Also small error corrections are done.
The code passed all tests for views, URLs, and forms.
@canberkboun9 , @oguzhandemirelx Can you review it?
=> Practice app/testing/article-info #108

practice-app/comment/tests.py, practice-app/comment/tests/test_forms.py, practice-app/comment/tests/test_models.py, practice-app/comment/tests/test_urls.py, practice-app/comment/tests/test_views.py, practice-app/comment/views.py
Unit tests for testing
- Views
- Models
- Forms
- URLs
are implemented. Current implementation passed all tests.
Related issue: #122
=> Unit Tests for the Comment Endpoint 

practice-app/post/templates/post_base.html, practice-app/post/templates/post_create.html, practice-app/post/templates/post_get.html, practice-app/post/templates/post_notfound.html
Done:
- Back now directs to ```../``` rather than ```localhost:8000/post```
- Home Page directs to ```../../``` rather than ```localhost:8000```
=> url direction of back and home page buttons changed to generalize

practice-app/article_info/templates/error_article_info.html, practice-app/article_info/templates/forms_article_info.html, practice-app/article_info/templates/updated_article_info.html, practice-app/article_info/templates/view_article_info.html
The bug about misdirections in the url when trying to go back are resolved by adding 'Home' and 'Back' buttons to the UI as mentioned in issue #144 :
* 'Home' directs to the main page of the app.
* 'Back' directs to the previous page.
@canberkboun9, @oguzhandemirelx Can you review it?
=> Practice-App/bug-fix/article-info-#144

practice-app/_main/templates/login.html, practice-app/user/templates/user.html, practice-app/user/tests/test_views.py, practice-app/user/views.py
* Sign-up button added
* Sign-up screen uses the User API functionalities
* Back to Main Page button added to User API Screen (in other words Sign-up screen)
* Look the issue #148 
* Some changes in User API that is related to deployment
=> Last changes for Practice App

practice-app/practice_app/urls.py, practice-app/rate_article/forms.py, practice-app/rate_article/serializers.py, practice-app/rate_article/templates/forms_rate_article.html, practice-app/rate_article/templates/view_rate_article.html, practice-app/rate_article/tests/test_forms.py, practice-app/rate_article/tests/test_urls.py, practice-app/rate_article/tests/test_views.py, practice-app/rate_article/urls.py, practice-app/rate_article/views.py
Rate Article part of the practice-app is implemented in the rate-article branch. Implementation and Unit Tests are included. Can someone review it? 
**Reviewers: @enginoguzhansenol , @busetolunay**
=> Rate article

practice-app/rate_comment/templates/formsratecomment.html, practice-app/rate_comment/urls.py, practice-app/rate_comment/views.py
I fixed the bugs for the rate-comment endpoint. Now, it should be all correct. Closes #156.
=> Bug fixed for conflicted URLs

practice-app/post/templates/post_create.html, practice-app/post/templates/post_get.html, practice-app/practice_app/urls.py, practice-app/rate_comment/tests/test_forms.py, practice-app/rate_comment/tests/test_urls.py, practice-app/rate_comment/tests/test_views.py
I finished the tests for the rate-comment. Also, there are changes made in other endpoints:
- The article-info path was added to the app.
- Back button in the post endpoint was corrected.
Closes #134.
=> Practice app/testing/rate comment #134

practice-app/category/views.py, practice-app/rate_article/tests.py, practice-app/rate_article/urls.py, practice-app/rate_comment/urls.py, practice-app/rate_post/tests.py, practice-app/rate_post/urls.py, practice-app/user/tests/test_views.py, practice-app/user/views.py
Some bugs related to unit tests are fixed.
- urls.py files of rate_article, rate_post, rate_comment endpoints are corrected. 
- An __init__.py file is added to rate_article/tests folder
- Some print statements causing prints during testing in user/views.py, user/tests/test_views.py and category/views.py files are removed.
=> Fixed Some Bugs Related to Tests

app/backend/requirements.txt
Requirements.txt was added to the repository to set up the virtual environment for the project.
- Requirements.txt added to the repository
- Can be used with the command 'pip install -r requirements.txt'
Issue: #195 
Reviewer: @canberkboun9
=> Reqirements added to repo

app/backend/backend/settings.py
Connection of the database to the Django app.
- Connection is done.
Issue: #197 
Reviewer: @mehmetemreakbulut
=> Django App Connection to the DB

app/backend/authentication/admin.py, app/backend/authentication/apps.py, app/backend/authentication/models.py, app/backend/authentication/tests.py, app/backend/authentication/urls.py, app/backend/authentication/views.py, app/backend/backend/settings.py, app/backend/backend/urls.py
- To identify the user of the coming request and manage authentication, an 'authentication' module inside the Django project is necessary. Also, implementing auth as a different module helps us to isolate the functionalities and some middleware. 
***Reviewer*:** @oguzhandemirelx 
***Notes*:** 
* Models related to authentication have been created on the core 'backend' module. Migrating them to the authentication module will be done later.
***Issue*:** 
* See #204
=> Authentication Module Created

.gitignore, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/widgets/ForumList.dart, app/mobile/bounswe5_mobile/lib/widgets/ForumPostItem.dart, app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart
Initial mobile home screen was created. It looks like this as of now:
|<img width="280" alt="Screen Shot 2022-10-25 at 12 27 50 (2)" src="https://user-images.githubusercontent.com/61624884/197737854-dd875a98-8446-4dc5-a7e8-9fb63ad8341e.png">|<img width="280" alt="Screen Shot 2022-10-25 at 12 37 14 (2)" src="https://user-images.githubusercontent.com/61624884/197742192-1617cb0a-5783-4325-847a-bab4bc2ad2f9.png">|
***Notes*:** 
* Since **.gitignore** file included a line _lib/_ and our flutter project is based on a folder named _lib/_, while pushing our commits, files under _lib/_ directory were ignored. To fix this issue, I removed this line form the _.gitignore_ file. It can create a conflict with other branches if we …
=> Mobile Home Screen is Created

app/mobile/bounswe5_mobile/lib/screens/signup.dart, app/mobile/bounswe5_mobile/pubspec.yaml
Initial implementation of the sign-up screen is added. The screen looks like as the following. Validations for the sign-up fields are also done.
***Issue*:** 
* See #193
=> Mobile/feature/sign up screen #193

app/backend/authentication/serializers.py, app/backend/authentication/urls.py, app/backend/authentication/views.py, app/backend/backend/models.py, app/backend/requirements.txt, app/backend/tests/test_models.py, app/backend/tests/test_views.py
- Documentation is ready on the [API Documentation Signup](https://github.com/bounswe/bounswe2022group5/wiki/Signup-API-Documentation) and [API Documentation](https://github.com/bounswe/bounswe2022group5/wiki/Login-API-Documentation). 
- Based on this documentation, it is necessary the signup and login endpoints are ready.
- I added User Manager to User Model because we created a custom user model. 
- Validations added to serializers.
- Tests are implemented for functionalities added.
***Reviewer*:** @irfanbozkurt 
***Notes*:** 
* Some initial tables from the database were removed. Now, auth_user table is our custom user table.
* Migrations were changed and squashed because token table had a foreign key to the wrong table.
***Issue*:** 
* See #218
=> login and signup endpoints finished

app/mobile/bounswe5_mobile/lib/screens/signup.dart
Branch field is added for doctor sign-up to align with the frontend.
***Issue*:** 
* See #221
=> Branch field is added for doctor sign-up.

app/mobile/bounswe5_mobile/lib/screens/login.dart
- Initial design for login page for mobile
- Login page for the users to log into their accounts
- @enginoguzhansenol 
**Notes:** 
- Necessary changes for redirecting to other pages will be done in the future with the help of mobile team.
***Issue*:** 
* See [#225](https://github.com/bounswe/bounswe2022group5/issues/225)
=> Mobile: Login Page initial design codes

app/mobile/bounswe5_mobile/ios/Flutter/Debug.xcconfig, app/mobile/bounswe5_mobile/ios/Flutter/Release.xcconfig, app/mobile/bounswe5_mobile/ios/Podfile, app/mobile/bounswe5_mobile/ios/Podfile.lock, app/mobile/bounswe5_mobile/ios/Runner.xcodeproj/project.pbxproj, app/mobile/bounswe5_mobile/ios/Runner.xcworkspace/contents.xcworkspacedata, app/mobile/bounswe5_mobile/lib/models/user.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/screens/login.dart, app/mobile/bounswe5_mobile/lib/screens/profile.dart, app/mobile/bounswe5_mobile/lib/screens/signup.dart, app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart, app/mobile/bounswe5_mobile/pubspec.lock
- Mobile screens are connected to each other. 
- While establishing these connections, some necessary modifications and corrections are made.
**Notes:** 
- These changes were implemented in [Mobile Meeting 2](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Meeting-2) with all of Mobile team's attandence.
- Some further changes will be necessary when the backend is deployed.
- And also some other improvements may be needed.
***Issue*:** 
* See [#229](https://github.com/bounswe/bounswe2022group5/issues/229)
=> Mobile screens are connected

app/backend/Dockerfile, app/backend/backend/settings.py, app/backend/docker-compose.yml, app/backend/requirements.txt
Now the application can be accessed via:
[http://ec2-3-87-119-148.compute-1.amazonaws.com:8000/admin](http://ec2-3-87-119-148.compute-1.amazonaws.com:8000/admin)
=> App dockerized and deployed

app/backend/authentication/views.py, app/backend/backend/settings.py, app/backend/requirements.txt
- Frontend faces some diffucilties when sending request to backend. CORS headers must be fixed to allow frontend to access our APIs.
- Configurations added to serializers.
***Reviewer*:** @oguzhandemirelx 
***Notes*:** 
***Issue*:** 
* See #238
=> Cors headers added

app/backend/authentication/urls.py, app/backend/authentication/views.py, app/backend/tests/test_views.py
- Frontend needs to validate the token when entering the app
- When the user still has the token, they can log in to the system without re-login. It is a 'remember me' functionality.
***Reviewer*:** @irfanbozkurt 
***Notes*:** 
***Issue*:** 
* See #236
=> Me endpoint added

app/backend/authentication/views.py
=> Small bug fix

app/frontend/src/layouts/NavBar/NavBar.css, app/frontend/src/layouts/NavBar/NavBar.js
- Navigation bar which will be common in all website is added.
- Includes Login, Logout, Signin buttons as well as the search bar.
@burakmert236 @yavuuzsameet @Oozankilic 
**Notes:** 
- The logout function has not implemented yet. It can be added when the backend functionalities are done.
***Issue*:** 
* See [#235](https://github.com/bounswe/bounswe2022group5/issues/235)
=> [Frontend] Navigation Bar as an upper layout added.

app/frontend/src/layouts/Article/Article.css, app/frontend/src/layouts/Article/Article.js
- Article cards need to be available to use on the homepage.
***Reviewer*:** @Oozankilic  
***Notes*:** @Keremgunduz7 article cards and articles are made available to use on the homepage, they can be reached out by importing Article.
***Issue*:** 
* See #241
=> article cards are added.

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/pubspec.lock, app/mobile/bounswe5_mobile/pubspec.yaml
- An API service class is added.
- A function handling the login API call is added.
- A function handling the register API call is added.
- A function handling the logout API call is added.
This modifications are done in [Mobile Meeting 3](https://github.com/bounswe/bounswe2022group5/wiki/Mobile-Meeting-3) with all mobile team's attendance.
***Reviewers*:** @palahb , @bbenginbestas  
***Issue*:** 
* See #240
=> API service class is added to the mobile app 

app/frontend/src/layouts/Forum/Forum.js
- Forum part of homepage is created to be integrated after all the parts of homepage are ready.
@Keremgunduz7, @yavuuzsameet, @burakmert236 
***Issue*:** 
* See [Creating Forum page - Frontend #223 ](https://github.com/bounswe/bounswe2022group5/issues/223)
=> Forum page is updated

app/frontend/src/layouts/NavBar/NavBar.js
- Added logout function into navigation bar.
- Added logout function into the logout button.
@burakmert236 @yavuuzsameet @Oozankilic 
**Notes:** 
***Issue*:** 
* See [#235](https://github.com/bounswe/bounswe2022group5/issues/235)
=> [Frontend] Navigation Bar logout function implemented.

app/mobile/bounswe5_mobile/lib/screens/signup.dart
- API call for signup is made.
- Some comment is added to the signup screen code.
***Reviewers*:** @enginoguzhansenol  
***Issue*:** 
* See #245
=> Register API call for mobile is handled

app/frontend/src/layouts/Article/Article.css, app/frontend/src/layouts/Forum/Forum.css
- Aligned Posts and Articles.
- Increased the widths of forum and article components.
***Reviewer*:** @yavuuzsameet @Oozankilic
**Notes:**   
***Issue*:**  * See [#257](https://github.com/bounswe/bounswe2022group5/pull/257)
=> [Frontend] Aligned Forum and Articles pages in the Homepage.

app/frontend/src/layouts/Article/Article.js, app/frontend/src/layouts/HomePage/HomePage.js
- Create Post button hide whenever user not logged in.
- Create Post button hide whenever user not logged in.
***Reviewer*:** @yavuuzsameet @Oozankilic @burakmert236 
**Notes:**   
***Issue*:**  * See [#265](https://github.com/bounswe/bounswe2022group5/issues/265)
=> [Frontend] Create Post button hide whenever user not logged in.

app/mobile/bounswe5_mobile/lib/screens/login.dart
- Login page should have symbols for better looking, and to synchronize with Sign-up page.
- Login page should give errors when entered unwanted input.
- PR is for enhancement of the code.
**Notes:** 
- The code is better and more understandable.
***Issue*:** 
* See [#261](https://github.com/bounswe/bounswe2022group5/issues/261).
=> [Mobile] Adding symbols and error messages when giving unwanted inputs in Login page

app/mobile/bounswe5_mobile/lib/screens/login.dart
- Description of the Pull Request and related task.
- Must state the why and the how for the change
- Must explain the purpose of the PR.
**Notes:** 
- Necessary token was returned to home page.
***Issue*:** 
* See [#271](https://github.com/bounswe/bounswe2022group5/issues/271).
=> [Mobile] Handling API requests and returning necessary token to home page.

app/mobile/bounswe5_mobile/lib/screens/profile.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileListItem.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileName.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileWidget.dart
Profile widgets are separated from the profile.
- @bbenginbestas 
***Issue*:** 
* See [Issue #207 ](https://github.com/bounswe/bounswe2022group5/issues/207)
=> Mobile/feature/profile #207

app/mobile/bounswe5_mobile/android/app/src/main/AndroidManifest.xml, app/mobile/bounswe5_mobile/lib/screens/login.dart
A bug causing printing usernames and passwords to the console in the login page and a bug causing internet connectivity problem in APKs in /android/app/src/main/AndroidManifest.xml file have been corrected.
***Tasks done*:**
***Reviewer*:** @enginoguzhansenol
=> [Mobile] Minor bug-fixes in the login page and AndroidManifest.xml

app/backend/backend/settings.py, app/backend/common/apps.py, app/backend/common/views.py, app/backend/requirements.txt
Regarding [this issue](https://github.com/bounswe/bounswe2022group5/issues/306)
=> [Backend] S3 Integration

app/mobile/bounswe5_mobile/android/app/build.gradle, app/mobile/bounswe5_mobile/android/app/src/main/AndroidManifest.xml, app/mobile/bounswe5_mobile/lib/main.dart, app/mobile/bounswe5_mobile/lib/screens/createArticle.dart, app/mobile/bounswe5_mobile/lib/screens/createPost.dart, app/mobile/bounswe5_mobile/pubspec.lock, app/mobile/bounswe5_mobile/pubspec.yaml
"Create Post" and "Create Article" pages should be implemented in the mobile application.
**Notes:** 
- Briefly explain the changes and crucial points inside the code.
***Issue*:** 
* See [Issue #294](https://github.com/bounswe/bounswe2022group5/issues/294)
=> [Mobile] Initial implementations of "create post" and "create article" pages #294

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/mockData.dart, app/mobile/bounswe5_mobile/lib/models/article.dart, app/mobile/bounswe5_mobile/lib/models/category.dart, app/mobile/bounswe5_mobile/lib/models/comment.dart, app/mobile/bounswe5_mobile/lib/models/doctor.dart, app/mobile/bounswe5_mobile/lib/models/member.dart, app/mobile/bounswe5_mobile/lib/models/memberInfo.dart, app/mobile/bounswe5_mobile/lib/models/user.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart
- Existing models have been updated in a way that they include all fields specified in the tables created by the Backend team.
- New models have been created.
- Mock data have been created. They do not properly represent their classes, but for now, in order to work with the pages, they are sufficient. We can edit them later if we want.
- @kardelendemiral 
**Notes:** 
- Although I tried to follow the table structures specified in the [Backend Meeting 2 Notes](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.2) and [Backend Meeting 3 Notes](https://github.com/bounswe/bounswe2022group5/wiki/Backend-Meeting-1.3), the models and mock data may not properly represent the actual structure and also they are subject to change …
=> [Mobile] Model updates and mock data creation

app/backend/forum/tests.py, app/backend/forum/urls.py, app/backend/forum/views.py
We need endpoints for upvoting and downvoting a post. Necessary endpoints and related tests are added.
***Reviewer*:** @irfanbozkurt  
**Notes:** 
- post/<int:id>/upvote and post/<int:id>/downvote endpoints implemented.
***Issue*:** 
* See [Issue #313](https://github.com/bounswe/bounswe2022group5/issues/313)
=> [Backend] Vote endpoints for Posts

app/backend/backend/settings.py, app/backend/forum/serializers.py, app/backend/forum/tests.py, app/backend/forum/urls.py, app/backend/forum/views.py
* Comment upvote and downvote endpoints have been added. It is very similar to post voting APIs. 
* Documentation of API will be added to API Documentation in Wiki.
* Test were implemented.
* See #324 
**Reviewer**: @canberkboun9  or @oguzhandemirelx
=> [Backend] Comment voting endpoints added

app/mobile/bounswe5_mobile/lib/mockData.dart, app/mobile/bounswe5_mobile/lib/models/article.dart, app/mobile/bounswe5_mobile/lib/models/doctor.dart, app/mobile/bounswe5_mobile/lib/models/member.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticleItem.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticlesList.dart
Since there was no Articles section in mobile app, I created articles items and created a list by using them to show in the home page. While creating the home page, I tried to be consistent with the mockup we created in [Scenario 3 of CMPE 352](https://github.com/bounswe/bounswe2022group5/wiki/Scenario-3). The articles home page now seems like this:
While implementing these changes, some changes were needed in the models and mock data. I also implemented those changes.
- @enginoguzhansenol 
***Issue*:** 
* See [#322](https://github.com/bounswe/bounswe2022group5/issues/322)
=> [Mobile] Articles home page is created

app/backend/user_profile/urls.py, app/backend/user_profile/views.py
Users can upvote posts, and anyone might want to retrieve which posts they upvoted.
***Todo's*:**
***Reviewer*:** @mehmetemreakbulut  
***Task Deadline*:** 28.11.2020 00.00
=> [Backend] Getting upvotes (post) of a user 

app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart
- View post, and view article have been implemented as talked in the mobile meetings.
**Reviewer**: @enginoguzhansenol
=> [Mobile] Post viewing page and article viewing page have been implemented

app/backend/user_profile/urls.py, app/backend/user_profile/views.py
Users can upvote articles, and anyone might want to retrieve which posts they upvoted.
***Todo's*:**
***Reviewer*:** @mehmetemreakbulut  
***Task Deadline*:** 28.11.2020 00.00
=> [Backend] Getting upvotes (articles) of a user

app/mobile/bounswe5_mobile/lib/main.dart, app/mobile/bounswe5_mobile/lib/mockData.dart, app/mobile/bounswe5_mobile/lib/models/post.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/screens/login.dart, app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticleItem.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticlesList.dart, app/mobile/bounswe5_mobile/lib/widgets/ForumPostItem.dart, app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart
Since app theme was not that consistent with the frontend and its blue accent is not that eye-pleasing, we needed to change it. I changed the app theme, implemented necessary color changes in the pages. While implementing these color changes, post and article reading pages have been updated completely to have a consistent view with the new theme.
**Notes:** 
- In the post reading page, comment widgets can be implemented as a separate class to work more easily.
- Having separate Doctor and Member models can be reevaluated since in some parts of the code, this situation creates some problems. Having a single User can be more appropriate, but I am not sure.
- Color selection guide for other team members to help them while …
=> [Mobile] App theme has been updated

app/backend/forum/views.py
* It's the last commit of #338 . I don't understand what happened exactly but this commit won't be applied on that branch.
* Not a complete PR. Assume this as just a follow up commit.
=> voting info added to post and comments

app/mobile/bounswe5_mobile/lib/screens/comments.dart, app/mobile/bounswe5_mobile/lib/screens/editprofile.dart, app/mobile/bounswe5_mobile/lib/screens/posts.dart, app/mobile/bounswe5_mobile/lib/screens/profile.dart, app/mobile/bounswe5_mobile/lib/screens/upvotes.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileListItem.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileWidget.dart
There must be new screens connected to profile page such as edit profile page and activity history pages for comments, upvotes, posts.
@bbenginbestas 
***Issue*:** 
* Closes #310.
=> [Mobile] Creating initial pages of activity history and edit profile

app/mobile/bounswe5_mobile/lib/screens/signup.dart
***[Mobile] KVKK and Document Upload for Signup added***
KVKK agreement and document upload functionality for sign-up should be added to the signup page.
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/293)
=> [Mobile] KVKK and Document Upload for Signup added

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/signup.dart
***[Mobile] Singup is finalized:***
Now that the signup endpoints for Member and Doctor are separated and updated, new API calls are made for registering of each user type. Doctor signup sends document to the endpoint. Registering functionality is working correctly right now.
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/352)
=> [Mobile] Singup is finalized

app/frontend/src/App.js, app/frontend/src/layouts/Article/Article.js, app/frontend/src/layouts/Forum/Forum.js, app/frontend/src/layouts/HomePage/HomePage.js, app/frontend/src/pages/Profile/Profile.css, app/frontend/src/pages/Profile/Profile.js, app/frontend/src/redux/articleSlice.js, app/frontend/src/redux/postSlice.js
- A profile page is created for frontend.
- User info and activity history display are implemented. 
- Posts are retrieved from backend, not static..
- Article Slice and Post Slice files are generated to retrieve data from backend.
- Homepage posts and articles are aligned with the slices.
@burakmert236 
@Keremgunduz7  
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/288)
=> [Frontend] Profile Page Implementation

app/backend/articles/urls.py, app/backend/articles/views.py
We need all articles for a doctor to show on his/her profile page. So we have to implement a get endpoint to fetch all articles for a doctor. Also we have to add new fields for get article method.
***Reviewer*:** @mehmetemreakbulut 
**Notes:** 
- Added a new endpoint for profile page. Enhanced get article endpoint. Related updates made on documentation.
***Issue*:** 
* See [Issue #353](https://github.com/bounswe/bounswe2022group5/issues/353)
=> [Backend] Get a doctor's all articles

app/backend/user_profile/tests.py, app/backend/user_profile/urls.py, app/backend/user_profile/views.py
- User should be able to see their personal info in their profile page, and also be able to update them. We didn't have these so these 2 endpoints are brand new.
- @mehmetemreakbulut 
**Notes:** 
- I didn't use serializer. Implemented simply with dictionaries.
- "-1" value is an indicator of null value that is going to be handled by Frontend and Mobile. It is discussed with @palahb and on the [Meeting 21.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-21.1#agenda) (Agenda 2.2).
- Didn't implemented unit tests, didn't try to use the APIs. Sending some requests to test the APIs would be generous of the reviewer.
***Issue*:** 
* See [Issue #316](https://github.com/bounswe/bounswe2022group5/issues/316)
=> [Backend] Get, Update Personal Info Implementation

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/createComment.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart
- Comment create functionality is added to the mobile application.
**Notes:** 
- Since the data on Post View page is still static, I could not test the functionality. If needed, modifications may be made later on when the functionality is tested. 
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/358)
=> [Mobile] Comment Create Functionality Added

app/backend/user_profile/views.py
* Little hotfix for last MR
* A part creates problem for deployment I changed them and tested. 
* Tested
=> [Backend ]hotfix for last mr

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/mockData.dart, app/mobile/bounswe5_mobile/lib/models/memberInfo.dart, app/mobile/bounswe5_mobile/lib/models/user.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart
Drawer has been updated to show username of a member, fullname of a doctor, and avatars/profile pictures.
**Notes:** 
- To use SVG pictures, I added a new library. pub get needed.
***Issue*:** 
* See [#382](https://github.com/bounswe/bounswe2022group5/issues/342)
=> [Mobile] Drawer has been updated. getUserInfo API function is redesigned.

app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticleItem.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticlesList.dart
- Dropdown has been added to Articles. It changes output depending on active user.
**Notes:** 
- Other necessary changes were made in different screens related to articles. ActiveUser has been added to constructors.
***Issue*:** 
* See [#388 ](https://github.com/bounswe/bounswe2022group5/issues/388)
=> [Mobile] ViewArticlePage dropdown has been added

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/createArticle.dart, app/mobile/bounswe5_mobile/lib/screens/createPost.dart, app/mobile/bounswe5_mobile/pubspec.lock, app/mobile/bounswe5_mobile/pubspec.yaml
Create post and create article are revised. API caller functions are updated sending category and tags. 
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/393)
=> [Mobile] Create post and create article are revised

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/comments.dart, app/mobile/bounswe5_mobile/lib/screens/editprofile.dart, app/mobile/bounswe5_mobile/lib/screens/posts.dart, app/mobile/bounswe5_mobile/lib/screens/profile.dart, app/mobile/bounswe5_mobile/lib/screens/upvotes.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileWidget.dart
Profile page and related pages connected to it are updated.
@bbenginbestas 
***Issue*:** 
* Closes #376.
=> [Mobile] Edit Page 

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/mockData.dart, app/mobile/bounswe5_mobile/lib/models/article.dart, app/mobile/bounswe5_mobile/lib/models/label.dart, app/mobile/bounswe5_mobile/lib/models/post.dart, app/mobile/bounswe5_mobile/lib/screens/articleOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/screens/postOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticleItem.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticlesList.dart, app/mobile/bounswe5_mobile/lib/widgets/ForumList.dart, app/mobile/bounswe5_mobile/lib/widgets/ForumPostItem.dart, app/mobile/bounswe5_mobile/pubspec.yaml
Home page now gets paginated posts and articles from the backend.
**Notes:** 
- Old ForumPostList and ArticlesList widgets are not used from now on. Due to pagination, a new approach for getting new posts/articles is implemented.
***Issue*:** 
* See [#391](https://github.com/bounswe/bounswe2022group5/issues/391)
=> [Mobile] Home page now gets posts and articles from the backend.

app/frontend/src/App.js, app/frontend/src/layouts/HomePage/HomePage.js, app/frontend/src/redux/categorySlice.js, app/frontend/src/redux/postSlice.js
bar is responsive and data fetched from backend as mentioned in issue: https://github.com/bounswe/bounswe2022group5/issues/301
=> [Frontend]Making categories bar homepage responsive

app/frontend/src/layouts/NavBar/NavBar.js, app/frontend/src/pages/Login/Login.js, app/frontend/src/pages/Profile/Profile.js, app/frontend/src/redux/profileSlice.js, app/frontend/src/redux/userSlice.js
- Some minor errors are fixed, mainly on profile but also some other files.
@burakmert236 
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/404)
Closes #404.
=> [Frontend] Profile Page Last Touches

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/main.dart, app/mobile/bounswe5_mobile/lib/mockData.dart, app/mobile/bounswe5_mobile/lib/models/article.dart, app/mobile/bounswe5_mobile/lib/models/comment.dart, app/mobile/bounswe5_mobile/lib/models/post.dart, app/mobile/bounswe5_mobile/lib/models/user.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/screens/postOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart, app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart, app/mobile/bounswe5_mobile/pubspec.yaml
Getting a single post and article from the backend when we touch a single post/article has been implemented. Some changes in other related pages have been implemented.
**Notes:** 
- Many pages and API functions have been changed. Please investigate them before changing these pages or functions.
***Issue*:** 
* See [#402](https://github.com/bounswe/bounswe2022group5/issues/402)
=> [Mobile] Show a single post/article by fetching them from backend

app/frontend/src/layouts/Article/Article.js, app/frontend/src/layouts/Forum/Forum.js, app/frontend/src/pages/CreatePost/CreatePost.js
- Category button to the post creation page added and post and article cards are handled.
@Keremgunduz7  
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/406)
Closes #406.
=> [Frontend] Category button and Post-Article cards

app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart
Bug related to comment dropdown has been handled. 
**Notes:** 
- Necessary function locations has been pointed for later uses.
***Issue*:** 
* See [#409](https://github.com/bounswe/bounswe2022group5/issues/409)
=> Necessary fixes have been implemented.

app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart, app/mobile/bounswe5_mobile/lib/widgets/ForumPostItem.dart, app/mobile/bounswe5_mobile/pubspec.yaml
Showing HTML in post and article pages has been implemented.
***Issue:*** 
- See https://github.com/bounswe/bounswe2022group5/issues/412
=> [Mobile] Showing HTML has been implemented.

app/frontend/src/components/Vote/Vote.js, app/frontend/src/pages/CreatePost/CreatePost.js
- Add labels button will be added to the create post page, and its functionality will be implemented.
***Reviewer*:** @Oozankilic    
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/416)
Closes #416.
=> [Frontend] Label Functionality Implementation

app/frontend/src/components/Vote/Vote.js
- Guest users were able to vote on the homepage, they should not be able to.
@burakmert236 
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/413)
Closes #413 .
=> [Frontend] Voting disabled for guest user

app/mobile/bounswe5_mobile/lib/main.dart, app/mobile/bounswe5_mobile/lib/screens/createArticle.dart, app/mobile/bounswe5_mobile/lib/screens/createPost.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/screens/login.dart, app/mobile/bounswe5_mobile/lib/screens/signup.dart, app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart
Post/Article delete implemented. Also some minor fixes are done. 
**Notes:** 
- Delete comment will be implemented later on.
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/360)
=> [Mobile] Post/Article Delete Implemented

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/articles.dart, app/mobile/bounswe5_mobile/lib/screens/posts.dart, app/mobile/bounswe5_mobile/lib/screens/profile.dart, app/mobile/bounswe5_mobile/lib/screens/upvotedArticles.dart, app/mobile/bounswe5_mobile/lib/screens/upvotedArticlesOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/screens/upvotedPosts.dart, app/mobile/bounswe5_mobile/lib/screens/upvotedPostsOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/screens/userArticleOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/screens/userPostOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileName.dart
Profile page and related pages connected to it are updated.
@palahb 
***Issue*:** 
* Closes #399.
=> [Mobile] Activity history is added

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/articles.dart, app/mobile/bounswe5_mobile/lib/screens/comments.dart, app/mobile/bounswe5_mobile/lib/screens/editprofile.dart, app/mobile/bounswe5_mobile/lib/screens/posts.dart, app/mobile/bounswe5_mobile/lib/screens/userCommentsOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/widgets/ProfileName.dart
Profile page and related pages connected to it are updated.
@kardelendemiral  
***Issue*:** 
* Closes #426 .
=> [Mobile] Comments Activity History 

app/frontend/src/components/Popup/Popup.css, app/frontend/src/pages/Profile/Profile.js
Profile Page is improved, user info editing and the display is variated and medical history for members is implemented.
*For Members*:
*For Doctors*:
***Reviewer*:** @Keremgunduz7     
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/423)
Closes #423.
=> [Frontend] Additions to the profile page

app/backend/articles/views.py, app/backend/forum/views.py
- As mentioned in #434 no functionality has beed changed but functions is more understandable and clear now.
- Forum and Post endpoints were refactored.
- @canberkboun9 
**Notes:** 
- No changes needed from view of frontend and mobile team
***Issue*:** 
* See [Issue #434](https://github.com/bounswe/bounswe2022group5/issues/434)
=> Backend/feature/refactoring #434

app/backend/forum/views.py
The code for searching is not dynamic at all. Adding new functionality is hard.
It's basically based on "category" and "keyword" information, but logic blocks make it very hard to read and add new things.
***Todo's*:**
***Reviewer*:** @oguzhandemirelx    
***Task Deadline*:** 17.12.2022 22:00
=> [Backend] Search query simplified

app/frontend/src/components/Popup/Popup.css, app/frontend/src/layouts/HomePage/HomePage.css, app/frontend/src/layouts/HomePage/HomePage.js, app/frontend/src/redux/categorySlice.js
- The categories are now can be followed if not followed yet or unfollowed if followed at the moment. 
***Reviewer*:** @Keremgunduz7      
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/448)
Closes #448.
=> [Frontend] Following and Unfollowing Categories 

app/frontend/src/components/Popup/Popup.css, app/frontend/src/pages/Profile/Profile.js
- The functionality of editing medical history for members is implemented. Users can now edit their medical history by adding new illness, allergy, disease, operation or drug.
- Popup display fixed.
***Reviewer*:** @burakmert236     
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/438)
Closes #438.
=> [Frontend] Medical History Editing

app/frontend/src/components/Popup/Popup.css, app/frontend/src/pages/CreatePost/CreatePost.css, app/frontend/src/pages/CreatePost/CreatePost.js
- The labels are displayed on the create post page after they are entered by the user who is creating the post. 
***Reviewer*:** @Oozankilic       
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/451)
Closes #451.
=> [Frontend] Visualizing labels

app/backend/annotation/annotation_schema.py, app/backend/annotation/views.py
Frontend team found two bug on annotation endpoints. I have fixed these bugs in this PR. 
***Reviewer*:** @oguzhandemirelx       
***Task Deadline*:** 24.12.2022 12:00
***Review Deadline*:** 24.12.2022 18:00
=> [Backend] Annotation Bugfix

app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/473)
=> [Mobile] Category label's for post and article

app/backend/articles/views.py, app/backend/forum/views.py
- The  PR https://github.com/bounswe/bounswe2022group5/pull/476 is closed. However, it is merged to master branch. So the changes of this branch are applied to master. Commits of this branch are visible in history. We couldn't understand why github says it is closed. Assume it is **merged.**
- PR Description available in https://github.com/bounswe/bounswe2022group5/pull/476
=> [Backend] Trivial PR for Unclosed PR (Exlanation)

app/frontend/package.json, app/frontend/src/pages/Article/Article.css, app/frontend/src/pages/Article/Article.js, app/frontend/src/pages/Post/Post.css, app/frontend/src/pages/Post/Post.js, app/frontend/src/redux/annotationSlice.js, app/frontend/yarn.lock
- Backend connections are implemented to save annotations in database and fetch saved ones from database.
- Users are now able to see other users' annotations.
- Users are now able to update and delete annotations.
- @yavuuzsameet 
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/457)
=> [Frontend] Implementing Backend Connections for Annotation Functionalities

app/frontend/package.json, app/frontend/src/pages/Article/Article.css, app/frontend/src/pages/Article/Article.js, app/frontend/src/pages/Post/Post.css, app/frontend/src/pages/Post/Post.js, app/frontend/yarn.lock
- Basic structure will be implemented to create annotations.
- Backend connections of this task will be implemented in another branch and pr.
- @Oozankilic
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/455)
=> [Frontend] Initialization of Annotation Creation

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/articleSearchByCategory.dart, app/mobile/bounswe5_mobile/lib/screens/articleSearchByKeyword.dart, app/mobile/bounswe5_mobile/lib/screens/articleSearchByName.dart, app/mobile/bounswe5_mobile/lib/screens/articleSearchOverview.dart, app/mobile/bounswe5_mobile/lib/screens/articleSearchResults.dart, app/mobile/bounswe5_mobile/lib/screens/createArticle.dart, app/mobile/bounswe5_mobile/lib/screens/createPost.dart, app/mobile/bounswe5_mobile/lib/screens/home.dart, app/mobile/bounswe5_mobile/lib/screens/postSearchByCategory.dart, app/mobile/bounswe5_mobile/lib/screens/postSearchByGeolocation.dart, app/mobile/bounswe5_mobile/lib/screens/postSearchByKeyword.dart, app/mobile/bounswe5_mobile/lib/screens/postSearchByName.dart, app/mobile/bounswe5_mobile/lib/screens/postSearchOverview.dart, app/mobile/bounswe5_mobile/lib/screens/postSearchResults.dart, app/mobile/bounswe5_mobile/lib/screens/searchArticle.dart, app/mobile/bounswe5_mobile/lib/screens/searchPage.dart, app/mobile/bounswe5_mobile/lib/screens/searchPost.dart
- Post and article search functionalities are implemented. 
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/458)
=> [Mobile] Search functionality implemented

app/backend/forum/views.py
We have implemented forum so that users will see categories that followed on top when they open the forum. However if user didn't follow any category endpoint creates problem and return 400
***Todo's*:**
***Reviewer*:** @mehmetemreakbulut 
***Task Deadline*:** 25.12.2022 20:00
***Review Deadline*:** 25.12.2022 22:00
=> [Backend] Get All Posts Bug

app/frontend/src/components/Delete/Delete.js, app/frontend/src/pages/Post/Post.css, app/frontend/src/pages/Post/Post.js, app/frontend/src/redux/deleteSlice.js
Post deletion for the frontend.
***Reviewer*:** @yavuuzsameet           
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/493)
Closes #493  .
=> [Frontend] Post Deletion implemented

app/frontend/package.json, app/frontend/src/App.js, app/frontend/yarn.lock
Chatbot integration for the frontend
***Reviewer*:** @Oozankilic          
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/466)
Closes #466 .
=> [Frontend] Integrating Chatbot on frontend.

app/frontend/src/pages/Profile/Profile.js, app/frontend/src/redux/profileSlice.js
- The account deletion functionality is implemented.
- The users are redirected to the homepage in a logged-out status, with their all information deleted.
***Reviewer*:** @Oozankilic          
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/499)
Closes #499.
=> [Frontend] Delete account feature

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/doctorProfile.dart, app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart, app/mobile/bounswe5_mobile/lib/widgets/DoctorProfileWidget.dart
Profile page for doctors that all the users can view is created. 
@palahb  
***Issue*:** 
* Closes #491 .
=> [Mobile] Redirecting to Doctor's Profile Page

app/mobile/bounswe5_mobile/lib/screens/categories.dart
- Initial design of categories page was made.
**Notes:** 
- For the API section of the page, I asked Burak for help. He will do some important sections of the screen, including API calls.
***Issue*:** 
* See [#460](https://github.com/bounswe/bounswe2022group5/issues/460)
=> [Mobile] Categories screen have been created

app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart
- Added categories to MyDrawer. The button redirects to followed categories.
**Notes:** 
- When opening mydrawer. now there will be categories tab above log-out. For categories tab to show, the user should be SIGNED IN.
***Issue*:** 
* See [#461 ](https://github.com/bounswe/bounswe2022group5/issues/461)
=> [Mobile] Adding categories to MyDrawer

app/frontend/src/App.js
ChatBot initialization made with BotId param to redirect the bot to Front Bot from Mobile Bot (Default)
***Todo's*:**
***Reviewer*:** @yavuuzsameet 
***Issue*:** 
* Closes #511  .
=> [Frontend] Add BotId as param while initializing.

app/frontend/.babelrc, app/frontend/jest.config.js, app/frontend/src/components/Popup/Popup.js, app/frontend/src/tests/popup.test.js
- The unit test for Popup component is implemented.
***Reviewer*:** @Keremgunduz7            
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/512)
Closes #512.
=> [Frontend] Popup component testing

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/mockData.dart, app/mobile/bounswe5_mobile/lib/models/category.dart, app/mobile/bounswe5_mobile/lib/models/user.dart, app/mobile/bounswe5_mobile/lib/screens/categories.dart
Category following functionality is ready in our mobile app. Categories can be reached through drawer. Then any category can be followed or unfollowed.
||
|-|
|<img src="https://user-images.githubusercontent.com/61624884/209579816-45140ed1-543b-471c-bb92-ea68743ba43f.png" alt="drawing" width="220"/>|
***Issue*:** 
* See https://github.com/bounswe/bounswe2022group5/issues/509
=> [Mobile] Category follow functionality has been implemented

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/viewPost.dart, app/mobile/bounswe5_mobile/pubspec.lock
Comment deletion functionality is added to the mobile application. A user is now able to delete his/her own comments.
***Issue*:** 
* See [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/456)
=> [Mobile] Comment deletion functionality implemented #456

app/backend/forum/tests.py
Task 4 in [Meeting 24.1](https://github.com/bounswe/bounswe2022group5/wiki/Meeting-24.1)
See [Pull Request #503](https://github.com/bounswe/bounswe2022group5/pull/503) for implementation.
- @oguzhandemirelx 
***Issue*:** 
* See [Issue #478](https://github.com/bounswe/bounswe2022group5/issues/478)
=> [Backend] Report unit tests

app/mobile/bounswe5_mobile/lib/screens/home.dart
There was a bug in post creation in post creation button in Home Screen. The button was directed to the chatbot screen.
***Todo's*:**
***Reviewer*:** @bbenginbestas      
***Issue*:** 
* Closes #524.
=> [Mobile] Bug fixed in home screen.

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/models/textAnnotation.dart, app/mobile/bounswe5_mobile/lib/screens/createTextAnnotation.dart, app/mobile/bounswe5_mobile/lib/screens/viewTextAnnotations.dart, app/mobile/bounswe5_mobile/lib/widgets/TextAnnotationItem.dart
Text annotations are now deletable. Necessary API function has been created, necessary model updates has been implemented, necessary page updates have also been implemented.
|||
|-|-|
|<img src="https://user-images.githubusercontent.com/61624884/209587763-6d77f412-b5f7-4780-9270-4283a6c8d551.png" alt="drawing" width="220"/>|<img src="https://user-images.githubusercontent.com/61624884/209587669-a269da8b-1205-4c89-a20d-b4daeef200bf.png" alt="drawing" width="220"/>|
***Issue*:** 
* See https://github.com/bounswe/bounswe2022group5/issues/520
=> [Mobile] Text annotation deletion has been implemented

app/mobile/bounswe5_mobile/lib/screens/home.dart
Reverts bounswe/bounswe2022group5#526.
There was a mistake in bug fix, instead of post, it was redirecting to article. It was fixed.
Reviewer: @enginoguzhansenol
=> Revert "[Mobile] Bug fixed in home screen."

app/mobile/bounswe5_mobile/lib/API_service.dart, app/mobile/bounswe5_mobile/lib/screens/articleSearchOverview.dart, app/mobile/bounswe5_mobile/lib/screens/postSearchOverview.dart, app/mobile/bounswe5_mobile/lib/screens/userPostOverviewScreen.dart, app/mobile/bounswe5_mobile/lib/widgets/ArticleItem.dart
- Bugs that I mentinoned in #531 have been solved. 
***Tasks Done***
***Issue*:** 
* https://github.com/bounswe/bounswe2022group5/issues/531
=> [Mobile] Overview screen bugs have been solved
