bounswe/bounswe2022group5

practice-app/user/urls.py
practice-app/user/views.py

After implementing essential functionalities of User API, some bugs has arisen. 
* Bugs are listed in the issue #87.
Bugs that is fixed:
- No error message as response to the creation of a user with username that already exists. 
- Can't reach data when POST request is sended as a row JSON from Postman.
- Allows password field to be empty
- Don't check whether email is taken or not
- No error message if user creation is failed
- Email is not mandatory currently, however email is required for external API.
- No email validation
Also endpoints are changed.
* New endpoint for listing all users and creating a user: user/api.
* New endpoint for showing a spesific user detail with given username: user/api/<str: username>.
* Structure of APIs  is same as mentioned in issue #81.
After review, we …

User API bugs are fixed

---

practice-app/post/templates/post_get.html
practice-app/post/views.py

**Done:**
- The case-insensitive country names were not working as expected. Just the first letter was changing. I fixed it. See relevant issue #135.
- The `localhost:8000` reference links are removed from the code and replaced by `../`

case-insensitive property fixed, final adjustments before deployment

---

app/mobile/bounswe5_mobile/lib/screens/signup.dart

A bug needed to be fixed after a user registers successfully.
- After sign-up, instead of a new login page, the login page under the sign-up page is opened.
- @enginoguzhansenol 
***Issue*:** 
* See [Issue #277](https://github.com/bounswe/bounswe2022group5/issues/277)

Login pages being on top of each other after sign-up is fixed

---

app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart

To create a user specific home page, user should be able to see his/her name or username or email. For our case, since just the email is available for an user, I needed to correct drawer head in a way that it shows the email of the user.
***Issue*:** 
* See [#279 ](https://github.com/bounswe/bounswe2022group5/issues/279)

[Mobile] Drawer head in the Home page is updated

---

app/backend/authentication/models.py
app/backend/authentication/serializers.py
app/backend/backend/utils.py
app/backend/tests/test_models.py

See  [this issue](https://github.com/bounswe/bounswe2022group5/issues/297)

[Backend] Code Refactor

---

app/backend/forum/views.py

When users created posts without image urls, it caused exception in the back end.
Now fixed.
***Reviewer*:** @canberkboun9  
**Notes:** 
- Caused by code trying to access request.data['image_urls'] when it didn't exist.
***Issue*:** 
* See [Issue #299](https://github.com/bounswe/bounswe2022group5/issues/299)

[Backend] Create post without image urls #299

---

app/backend/forum/urls.py
app/backend/forum/views.py

We have two endpoints to fetch posts: get by id and get all with pagination.
However, users might need to fetch posts created by a specific user.
***Todo's*:**
***Reviewer*:** @mehmetemreakbulut  
***Task Deadline*:** 28.11.2020 00.00

[Backend] Getting all posts of a user

---

app/mobile/bounswe5_mobile/lib/API_service.dart
app/mobile/bounswe5_mobile/lib/models/user.dart
app/mobile/bounswe5_mobile/lib/screens/home.dart

Floating action button in the home page that is at the bottom left corner of the screen has been redesigned to be used while creating an article also. Necessary activation and user type checks have been implemented.
**Notes:** 
- API function that is called when the home page is called should be redesigned. It is now returning only user data, but we need posts and articles also. This change will affect this button also since `snapshot.data` is designed in a way that it only has User info right now.
***Issue*:** 
* See [#341](https://github.com/bounswe/bounswe2022group5/issues/341)

[Mobile] Floating action button for post/article creation is implemented

---

app/mobile/bounswe5_mobile/lib/API_service.dart
app/mobile/bounswe5_mobile/lib/main.dart
app/mobile/bounswe5_mobile/lib/screens/home.dart
app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart
app/mobile/bounswe5_mobile/lib/screens/viewPost.dart
app/mobile/bounswe5_mobile/lib/widgets/ArticleItem.dart
app/mobile/bounswe5_mobile/lib/widgets/ArticlesList.dart
app/mobile/bounswe5_mobile/lib/widgets/ForumList.dart
app/mobile/bounswe5_mobile/lib/widgets/ForumPostItem.dart
app/mobile/bounswe5_mobile/lib/widgets/MyDrawer.dart

From home page, there was no connection to post/article reading/creation pages. I have implemented these connections. 
**Notes:** 
- From the home page, user instance can be sent to every connected page, no need to make an API call to get user info from these pages.
- From now on, API connections should be implemented.
- API function that is called when the home page is called should be redesigned. It is now returning only user data, but we need posts and articles also. This change will affect this button also since `snapshot.data` is designed in a way that it only has User info right now.
***Issue*:** 
* See [#342](https://github.com/bounswe/bounswe2022group5/issues/342)

[Mobile] Necessary page connections in the home page have been implemented

---

app/mobile/bounswe5_mobile/lib/screens/viewPost.dart

- Some bugs have been fixes at ViewPostPage.
**Notes:** 
- Constructor requiring 'activeUser' field was already implemented by my teammates, so I just tested it.
***Issue*:** 
* See [#386 ](https://github.com/bounswe/bounswe2022group5/issues/386)

[Mobile] ViewPostPage bug fixes

---

app/mobile/bounswe5_mobile/lib/screens/viewPost.dart

- Dropdowns have been added to Posts and Comments. For posts, it changes depending on the active user.
@palahb 
**Notes:** 
- For comments, dropdowns will change according to the author of comments with the API.
***Issue*:** 
* See [#387 ](https://github.com/bounswe/bounswe2022group5/issues/387)

[Mobile] ViewPostPage dropdowns have been added

---

app/mobile/bounswe5_mobile/lib/screens/createComment.dart
app/mobile/bounswe5_mobile/lib/screens/viewPost.dart

Post page is updated after comment creation.
***Notes***
- After a comment creation, comment creation and old post page is popped and then new post page is pushed. This creates a kind of imperfect navigation animation. This can be handled in later PRs.
***Issue:*** 
- See https://github.com/bounswe/bounswe2022group5/issues/411

[Mobile] Updating post page after new comment

---

app/backend/user_profile/views.py

- User should be able to see their age in their profile page, and also be able to update them. I changed the code for age part. Now it's calculated instead of user changing it manually.
- @mehmetemreakbulut 
**Notes:** 
- I think that age field is not needed for a user in the database.
***Issue*:** 
* See [Issue #430](https://github.com/bounswe/bounswe2022group5/issues/430)

[Backend] Personal Info API Bugfix

---

app/backend/forum/views.py

Based on my research last week (see finalized results [here](https://github.com/bounswe/bounswe2022group5/issues/440)), today I decided to implement [Spherical Law of Cosines in a query](https://en.wikipedia.org/wiki/Spherical_law_of_cosines) for distance-based search queries.
Here's the query:
***Todo's*:**
***Task Deadline*:** 17.12.2022 22:00

[Backend] Post search based on distance

---

app/backend/articles/views.py
app/backend/forum/views.py
app/backend/user_profile/tests.py
app/backend/user_profile/views.py

- APIs that give Upvoted Articles and Posts as response work with token and naturally user_id can not be used. Doctor profile pages are implementing now and this data should be fetched.
- User id added to endpoints. When user_id is given upvoted articles or posts of this user will be in response, otherwise upvoted articles or posts of user requested will be in response.
- Author schema added to `get_comments_of_user`, `get_posts_of_user` and `get_articles_of_user` endpoints instead of author_id.
- See #467 
***Notes*:**
- After this PR, Upvoted Posts and Upvoted Articles endpoints can consume `user_id` in query parameters to fetch upvoted posts or articles of a certain user.
***Reviewer*:** @oguzhandemirelx    
***Task Deadline*:** 24.12.2022 12:00 …

[Backend] Fetching Upvoted Articles and Post by User Id

---

app/frontend/src/components/Popup/Popup.css
app/frontend/src/layouts/HomePage/HomePage.css
app/frontend/src/layouts/HomePage/HomePage.js
app/frontend/src/pages/Post/Post.js

- The suggested labels are attached to posts and displayed on the post pages.
- Redirection of labels is handled.
- Two UI improvements were added as described below in the last two elements.
***Reviewer*:** @Keremgunduz7         
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/483)
Closes #483.

[Frontend] Ontology suggestion labels and UI fix

---

app/frontend/src/components/Delete/Delete.js
app/frontend/src/pages/Article/Article.css
app/frontend/src/pages/Article/Article.js
app/frontend/src/pages/CreateArticle/CreateArticle.js
app/frontend/src/pages/CreatePost/CreatePost.js
app/frontend/src/pages/Post/Post.js
app/frontend/src/pages/Profile/Profile.js
app/frontend/src/redux/deleteSlice.js

- The article deletion functionality is implemented.
- The users are redirected to the homepage after the delete operation.
- Some minor fixes as described in the last two elements.
***Reviewer*:** @burakmert236           
***Issue*:**  [Issue Link](https://github.com/bounswe/bounswe2022group5/issues/501)
Closes #501.

[Frontend] Article deletion and bug fixing

---

app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart

Article page redirection bug has been fixed. After closing annotations screen, user is redirected to the article page.
***Issue*:** 
* https://github.com/bounswe/bounswe2022group5/issues/521

[Mobile] Article page redirection bug has been fixed

---

app/mobile/bounswe5_mobile/lib/API_service.dart
app/mobile/bounswe5_mobile/lib/screens/viewArticle.dart
app/mobile/bounswe5_mobile/lib/screens/viewPost.dart

From now on, labels can be seen in the article/post reading pages.
***Tasks Done***
***Issue*:** 
* https://github.com/bounswe/bounswe2022group5/issues/522

[Mobile] Labels shown in the post/article viewing page

---

app/mobile/bounswe5_mobile/lib/screens/chatbotScreen.dart

A chatbot for mobile is created. The AppID of the Chatbot variable is changed to the Mobile Chatbot. Since Chatbot response can only return to an URL, redirecting to the relative category cannot be done for mobile.
***Todo's*:**
***Reviewer*:** @palahb       
***Issue*:** 
Closes #529.

[Mobile] Bug Fix in Chatbot
